### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ravirathore** [btk/vectorizer#2]
Hi,

This software looks great. Just wanted to give one suggestion:

In the picture below, result on right shows output of '4 steps'. As, in this case, output has used red color a lot, is it possible to tell it that when it fills the image with red color, it should use some gradients of red color too, instead of using the same red color everywhere. It will help the software in enrichening the image better without deciding/thinking about adding a new color(fifth color) and finding the places where to use it.

![Capture1](https://user-images.githubusercontent.com/19185692/203048128-ae8fdbb8-2a7d-44c3-8668-dbfd6f970cf3.PNG)

regards,

**Comment by btk** [comment]
Hey, thank you for the suggestion! 

I'm planning a nice color editor/mixer as an addition on the output, based on https://github.com/btk/svg-color-editor

**Comment by ravirathore** [comment]
Thanks

**Comment by ravirathore** [comment]
@btk 

Hi,

I want to work on this project further. Can you suggest me some research papers references, or anything related to the algorithms, around this topic? 

Any help would be appreciated.

Thanks,
